class Items {
  items = {
    'Medkit': { 
      name: 'Medkit',
      item_type: 'heal',
      apply: true,
      heal_type: 'instant',
      heal_amount: 30,
      draft_rarity: 'uncommon',
      value: 50,
    },
    'Suture Kit': {
      name: 'Suture Kit',
      item_type: 'limb_restore',
      apply: true,
      restore_type: 'instant',
      restore_amount: 5,
      draft_rarity: 'uncommon',
      value: 30,
    },
    'Neuro Restore': {
      name: 'Neuro Restore',
      item_type: 'revive',
      apply: true,
      revive_type: 'instant',
      revive_amount: 5,
      draft_rarity: 'rare',
      value: 50,
    },
    'Broadhead Crossbow Bolt': {
      name: 'Broadhead Crossbow Bolt',
      item_type: 'ballistic_bolt_ammo',
      apply: false,
      base_damage: 10,
      max_stack_size: 10,
      stack_size: 1,
      draft_rarity: 'common',
      value: 2,
    },
    'Hollow Point Pistol Ammo': {
      name: 'Hollow Point Pistol Ammo',
      item_type: 'ballistic_pistol_ammo',
      apply: false,
      base_damage: 15,
      max_stack_size: 20,
      stack_size: 1,
      draft_rarity: 'uncommon',
      value: 3,
    },
    'Sport Pistol Ammo': {
      name: 'Sport Pistol Ammo',
      item_type: 'ballistic_pistol_ammo',
      apply: false,
      base_damage: 8,
      max_stack_size: 20,
      stack_size: 1,
      draft_rarity: 'common',
      value: 1,
    },
    'Homemade Energy Cell': {
      name: 'Homemade Energy Cell',
      item_type: 'energy_cell',
      apply: false,
      energy_charge: 5,
      draft_rarity: 'common',
      value: 1,
    },
    'Small Fuel Canister': {
      name: 'Small Fuel Canister',
      item_type: 'elemental_ammo',
      apply: false,
      element: 'fire',
      max_stack_size: 5,
      stack_size: 5,
      draft_rarity: 'uncommon',
      value: 5,
    },
    'PDA': {
      name: 'PDA',
      item_type: 'tool',
      apply: true,
      skill_bonus: 'hacking',
      bonus_amount: 1,
      draft_rarity: 'common',
      value: 10,
    },
    'Basic Stim Patch': {
      name: 'Basic Stim Patch',
      item_type: 'stim',
      apply: true,
      draft_rarity: 'common',
      buffs: [
        {'buff_type': 'ap',
        'buff_duration': 3,
        'buff_amount': 1,
        'buff_delay': 0,
        }
      ],
      'debuffs': [
        {'debuff_type': 'ap',
        'debuff_delay': 4,
        'debuff_amount': 1,
        'debuff_duration': 5}
      ],
      value: 10,
    },
    'Simple Repair Kit': {
      name: 'Simple Repair Kit',
      item_type: 'repair',
      apply: true,
      repair_type: 'instant',
      repair_amount: 15,
      draft_rarity: 'common',
      value: 10,
    },
    'HE Grenade': {
      name: 'HE Grenade',
      item_type: 'throwable',
      apply: false,
      damage_type: 'explosive',
      damage_radius: 1,
      damage_amount: 10,
      draft_rarity: 'rare',
      value: 50,
    },
    'Sport Rifle Ammo': {
      name: 'Sport Rifle Ammo',
      item_type: 'ballistic_rifle_ammo',
      apply: false,
      base_damage: 15,
      max_stack_size: 15,
      stack_size: 1,
      draft_rarity: 'uncommon',
      value: 2,
    },
  }
}

export default Items