class Weapons {
    weapons = {
        "combat_knife": {
            name: "Combat Knife",
            range: 1,
            uses_ammo: false,
            ammo_type: null,
            ammo: [],
            max_ammo: 0,
            reload_ap: 0,
            attacks: {
                'slash': {
                    ap_cost: 1,
                    base_damage: 4,
                    range: 1,
                    base_accuracy: 20,
                    fatigue_damage: 1, 
                    fatigue_cost: 1,
                    max_ammo_used: 0,
                    skill: "slash_and_stab",
                    attack_type: "melee",
                    damage_type: "ballistic",
                },
                'stab': {
                    ap_cost: 2,
                    base_damage: 6,
                    range: 1,
                    base_accuracy: 10,
                    fatigue_damage: 1, 
                    fatigue_cost: 1,
                    max_ammo_used: 0,
                    skill: "slash_and_stab",
                    attack_type: "melee",
                    damage_type: "ballistic",
                }
            }
        },
        "heavy_tool": {
            name: "Heavy Tool",
            range: 1,
            uses_ammo: false,
            ammo_type: null,
            ammo: [],
            max_ammo: 0,
            reload_ap: 0,
            attacks: {
                'smash': {
                    ap_cost: 2,
                    base_damage: 8,
                    range: 1,
                    base_accuracy: 10,
                    fatigue_damage: 10, 
                    fatigue_cost: 4,
                    max_ammo_used: 0,
                    skill: "bash_and_bludgeon",
                    attack_type: "melee",
                    damage_type: "blunt",
                },
            }
        },
        "makeshift_pistol": {
            name: "Makeshift Pistol",
            range: 3,
            uses_ammo: true,
            ammo_type: "ballistic_pistol",
            ammo: [],
            max_ammo: 1,
            reload_ap: 3,
            attacks: {
                'snap shot': {
                    ap_cost: 1,
                    base_damage: 10,
                    range: 4,
                    base_accuracy: 5,
                    fatigue_damage: 2, 
                    fatigue_cost: 1,
                    max_ammo_used: 1,
                    skill: "handguns",
                    attack_type: "ranged",
                    damage_type: "ballistic",
                },
                'aimed shot': {
                    ap_cost: 3,
                    base_damage: 10,
                    range: 4,
                    base_accuracy: 20,
                    fatigue_damage: 2, 
                    fatigue_cost: 1,
                    max_ammo_used: 1,
                    skill: "handguns",
                    attack_type: "ranged",
                    damage_type: "ballistic",
                },
                'smack': {
                    ap_cost: 1,
                    base_damage: 4,
                    range: 1,
                    base_accuracy: 10,
                    fatigue_damage: 5, 
                    fatigue_cost: 2,
                    max_ammo_used: 0,
                    skill: "bash_and_bludgeon",
                    attack_type: "melee",
                    damage_type: "blunt",
                }
            },
        },
        "makeshift_rifle": {
            name: "Makeshift Rifle",
            range: 3,
            uses_ammo: true,
            ammo_type: "ballistic_rifle",
            ammo: [],
            max_ammo: 1,
            reload_ap: 4,
            attacks: {
                'snap shot': {
                    ap_cost: 1,
                    base_damage: 20,
                    range: 8,
                    base_accuracy: 5,
                    fatigue_damage: 3, 
                    fatigue_cost: 1,
                    max_ammo_used: 1,
                    skill: "marksmanship",
                    attack_type: "ranged",
                    damage_type: "ballistic",
                },
                'aimed shot': {
                    ap_cost: 4,
                    base_damage: 20,
                    range: 8,
                    base_accuracy: 25,
                    fatigue_damage: 3, 
                    fatigue_cost: 1,
                    max_ammo_used: 1,
                    skill: "marksmanship",
                    attack_type: "ranged",
                    damage_type: "ballistic",
                },
                'smash': {
                    ap_cost: 2,
                    base_damage: 8,
                    range: 1,
                    base_accuracy: 10,
                    fatigue_damage: 10, 
                    fatigue_cost: 4,
                    max_ammo_used: 0,
                    skill: "bash_and_bludgeon",
                    attack_type: "melee",
                    damage_type: "blunt",
                },
            },
        }
    }
}

export default Weapons